### ISSUE TITLE
feat (UI -> Tools): Connect the Trim and Conceal slider's marks into map

### ISSUE THREAD

**Issue by muktihari** [openivity/openivity.github.io#56]
Currently when we slide the input range of trim and conceal feature, we only get feedback on how much distance that we trim/conceal and the resulting new distance. We need to know the point A to B of selected distance in the map so we get better understanding of how much that we actually want to trim/conceal.

Specification:
1. Mark the route for (`beginning of the route` to `selected start`) and (`selected end` to `end of the route`), this can be achieved by sending it as LineString features to be rendered by ol.Map, the zIndex should be above route.
2. The marks for trim and conceal must be able to be differentiated by our eye. Suggestion add a little bit transparent (e.g. opacity: 0.8)
3. For mobile device, add a modal to expand the selection in a different pop up page containing only the map at top and the slider at bottom, add a "save" or "done" button to get back to previous page. This way, user can focus on sliding in the limited space of mobile device.

**Comment by raditzlawliet** [comment]
![image](https://github.com/openivity/openivity.github.io/assets/3763178/03acbf42-2208-48d3-af98-97f1ca836562)
can we have this as reference?
- The transparent or more dark-grey on conceal. The result will be not transparent (or still looks same with in map)
- Current path map use another color like Title (#f15a22), so it will looks easy to differentiate

**Comment by muktihari** [comment]
Yes, we can have this as reference and adding similiar icon will be good too.
For color, we can do trial and error and see which best to use, need to differentiate color between trim & conceal.

**Comment by muktihari** [comment]
I think I will be working on this one if you don't mind @raditzlawliet ?

**Comment by raditzlawliet** [comment]
> I think I will be working on this one if you don't mind @raditzlawliet ?

Sure, 
if you're have another issue, I also can pick up on this too, 
just inform me.

**Comment by muktihari** [comment]
Oh if you interested on this one you can pick this up, since you have already have suggestions in previous comment as well.
I will pick #72 then?

**Comment by raditzlawliet** [comment]
Okay, Let me pick up this and you can go continue on #72

**Comment by raditzlawliet** [comment]
Btw, How about trim and conceal and have some case like...
- A e.g., What if trimmed distance more short than conceal?
- B e.g., What if conceal distance more short than trimmed?

I Think, conceal is more nulling the location of record and trim di to cutout the record. 
since two of them are can have impact, conceal gps distance (or marker) value should be within trim/cutout distance. cmiiw

**Comment by muktihari** [comment]
> A e.g., What if trimmed distance more short than conceal?

On this case (in backend), we will conceal from ConcealStart up to TrimStart

> B e.g., What if conceal distance more short than trimmed?

On this case, nothing will be concealed since it will be trimmed anyway


We rely on user common sense to apply and also it's simplicity for us as developer. Let's just have slightly different color on conceal and trim marker so user know which one is the marker.

**Comment by raditzlawliet** [comment]
Ok, let use this one, we use different color for conceal and trim

**Comment by muktihari** [comment]
Sure, we can also make conceal layer below trim layer, so the conceal will be covered by the trim. You can add bit of opacity like 0.9 to make the overlap noticeable, but it's up to you which one you think is best.
