### ISSUE TITLE
[HOLD] Make HR Zone to only include records that considered moving if it's an Outdoor Workout.

### ISSUE THREAD

**Issue by muktihari** [openivity/openivity.github.io#57]
When we workout, we care more about when we are actually moving rather than when we are at rest or stationary.
This current implementation is calculating all record without considering is user actually moving or not.

<img width="350" alt="Screen Shot 2023-12-01 at 22 30 31" src="https://github.com/openivity/openivity.github.io/assets/15964188/c16e7e07-7748-4b87-a619-b6db1e63dcb5">

But how do we know whether user is moving? In our BE logic, the algorithm is like this:
<img width="566" alt="Screen Shot 2023-12-01 at 22 33 41" src="https://github.com/openivity/openivity.github.io/assets/15964188/ec572955-9d4e-4242-9649-c7e39c55655b">

I realised I'm missing a little bit detail here, before checking the speed I should have determine whether the workout is indoor or outdoor by checking if the `PositionLat` and `PositionLong` is exist at least in one record (per session), no Lat/Long mean no GPS so we can consider it as indoor workout. 

- If it's an indoor workout, it's ok to include all records (no need to check IsConsideredMoving). 
- If it's an outdoor workout  we only include moving records. 

I will update BE code later but I hope you got the idea. I think I should expose how much speed is considered moving for each sport, I will add new endpoint so we always get the same number when we change the constant at BE should reflect on FE. But for now let's work concurrently to achieve this goal.

**Comment by muktihari** [comment]
I will consider to add field `isIndoor` field in `Session` struct, since I will do the checking in BE, so FE does not have to do it again, wdyt @raditzlawliet ?

**Comment by muktihari** [comment]
Let me clarify this, IsConsideredMoving is filtering record that's too slow for particular sport, the data is from sampling so it only sample, for example, Speed at this Timestamp. For that sample, the speed can be below threshold that we consider that moving but it's still being recorded. 

Most common use case, we do cycling but we feel tired at some points and choose to walk. XOSS may pause the recording at specific time but some records are still being recorded before the complete pause or sometimes, the pause is only for temporary so it will auto-play-pause again making the data more "dirty".

The algorithm in BE is the result of matching the calculation of MovingTime (from various sports) from our service with Strava as a benchmark. The reason why we have this in the first place is initially because, unlike FIT, we do our own summary calculation for GPX and TCX since they don't have summary in the file. The current implementation of the algorithm is free to be challenged, but for now it's arguably the nearest result with the benchmark, Strava.

**Comment by muktihari** [comment]
Some platforms has their own methods to calculate the any data (distance, speed, etc), so the approach may be different and the result most likely be different, but the gap is commonly not that big. It's because we relly on sampling data from the GPS which is not really that accurate. That's also the reason why marathon track is always calculated manually, not using GPS-based tool like gmap or komoot.

It's okay to be slightly differ, it's something that many platforms try to improve as they go.

**Comment by muktihari** [comment]
- use IsConsiderMoving (so all indoor door will set true from BE)

We need to consider the latency between wasm-js if we call the function for every records, it's usually better to have all-wasm or all-js. The option that I can provide is the constant per sport, so that you can replica the function in js.


- check sport from each session is it indoor or outdoor based on registered data (do we have this?)


No, we don't have, that's why I propose to add new field 'isIndoor' each session, so if it's true then we can just include all records without checking it again. But for now we can do it concurrently ya, check in FE for now.

**Comment by raditzlawliet** [comment]
> * use IsConsiderMoving (so all indoor door will set true from BE)
> 
> We need to consider the latency between wasm-js if we call the function for every records, it's usually better to have all-wasm or all-js. The option that I can provide is the constant per sport, so that you can replica the function in js.

Do current record that already processed from wasm include data `IsConsiderMoving`? 
i suggest to use single source of truth so between it already set the data from wasm or js. IF wasm-service already able OR use, it better to put in wasm.

> No, we don't have, that's why I propose to add new field 'isIndoor' each session, so if it's true then we can just include all records without checking it again. But for now we can do it concurrently ya, check in FE for now.

For now, seems ok. This rule also need to applied all component that display Moving time (summary, etc.). 
And keep in mind also it has "possibility" to re-change again in the future (move to all-wasm as data property)

**Comment by muktihari** [comment]
> Do current record that already processed from wasm include data IsConsiderMoving?

Wasm only process it for calculating totalMovingTime in Lap and Session. If we add new field as a flag whether its moving in Record, this will significantly add bottleneck in interop between wasm-js (which is already huge) as the size of data will be multiplied. Please do some experiment on it and you will notice the difference. Coding for wasm is a different with coding for server. This is the trade-off that we should choose.

The viable options that I can think of are:
- Just loop it again in js, it's cheaper that way, as long as we have the same constant, the result will always same and still considered one single source of truth. The change of algorithm will be less frequent anyway.

- Do the calculation of HR Zone entirely in wasm, exposing new endpoint be called from js and only return what you need. This is less expensive too.

**Comment by muktihari** [comment]
Actually for FIT file, we have sub-sport that can give us more detail, include if it's indoor or not, but this can't be taken for granted since we still don't have any FIT file sample generated from indoor training devices such as treadmill and smart trainer indoor cycling. Currently we ignore this field, since it's only available for FIT files. We do still need a method for check (and add flag in Session) for GPX and TCX files as well as to double check the FIT file if some device not fill it properly.

<img width="626" alt="image" src="https://github.com/openivity/openivity.github.io/assets/15964188/78231963-80aa-4014-9e7b-2febc9dc445b">

**Comment by raditzlawliet** [comment]
Actually do in the wasm is your suggest (all-wasm), if it already know the cons, then just do the way with greatest pros.

No need to make it complex for now, as the problem is how to calculate Moving Time (and for now the problem is only in HR Zone). We can do that now, Please conclude it in next comment

**Comment by muktihari** [comment]
Ok, please move the HR Zone calculation that's currently on `js` to `wasm`, after I completed issue #59 ya. I have cached last decoded activities in `wasm` you can use that for faster process, no need to re-decode it.

**Comment by muktihari** [comment]
Oh I thought you want to do it in wasm, lol
Actually I am giving you the options so please choose what's more suitable for your case.

**Comment by raditzlawliet** [comment]
No problem, since wasm already put the movingTolerance #60 , Let's decide implement the calc in JS first and we'll see if there a room for improvement

**Comment by muktihari** [comment]
Wait, let put this issue on hold first, I want to confirm something relating this, so we don't work twice later.

**Comment by muktihari** [comment]
I believe I misunderstood how hr zone is calculated, it should have include all records, so the current algorithm for including all records is already correct. I'll close this ticket and takes more research regarding this.
