### ISSUE TITLE
Multiple Session with Different sport and sensor have funny behavior/display on some graph

### ISSUE THREAD

**Issue by raditzlawliet** [openivity/openivity.github.io#73]
When try using combined fit with multiple session
- cycling: has location, speed, cadence, hr, elev
- running: has location, pace, speed

The result is like minus or infinity minus. It still good sih, but maybe we can set 0 instead?
![image](https://github.com/openivity/openivity.github.io/assets/3763178/d4bf4119-acda-4d34-8536-9913899da94d)

Another things, something weird when hovering with mouse, it snap to next session and can't hover last part of current session
https://github.com/openivity/openivity.github.io/assets/3763178/0c396718-fa6a-4578-8c6e-43cbdf67274f

**Comment by muktihari** [comment]
Before we take a look on this issue, please conceal any map reference for privacy, please update the picture reference especially when it's not related to the map.

**Comment by raditzlawliet** [comment]
Sure, I've made it conceal

**Comment by muktihari** [comment]
Thanks, I'll take a look on this.

**Comment by muktihari** [comment]
This happen because we treat is a 0 when the minimum y is 100 for example, so it's like a minus. Already push a PR ya.
