### ISSUE TITLE
Wrong Trim/Conceal Icon, should be black

### ISSUE THREAD

**Issue by muktihari** [openivity/openivity.github.io#84]
Expected:
<img width="250" alt="image" src="https://github.com/openivity/openivity.github.io/assets/15964188/b8d484e1-ac10-4d3d-a3bd-c693ed52cd00">

Got:
<img width="280" alt="image" src="https://github.com/openivity/openivity.github.io/assets/15964188/b105cc18-3221-460a-a8b4-d979c5e39eaa">

**Comment by raditzlawliet** [comment]
Oh, i got the file swapped on my side

**Comment by raditzlawliet** [comment]
fixed directly into `dev`

**Comment by muktihari** [comment]
> fixed directly into dev

Okee, thanks you!

**Comment by muktihari** [comment]
close #84
