### ISSUE TITLE
Update Readme or Wiki and Merge to Master

### ISSUE THREAD

**Issue by raditzlawliet** [openivity/openivity.github.io#88]
Since Openivity can be use now, How about we update the Readme with major points:
- Openivity: About
- Getting Started: How to try the tools (and/or don't forget to star project)
- Features / Key Points Feature: What features available on Openivity (current)
- Building: How to build and start locally
- Contributing: Plain or Link to Wiki how to contributing and contributor list
- License

and, we merge all development into master. 
finally, we move build to master and use semantic version for online versioning.

**Comment by muktihari** [comment]
Sorry for late reply, I just read this issue's comment, I already add these following items:
- LICENSE file
- Update README.md containing:
  - About
  - Getting Started
  - Prerequisites
  - How to build and start locally

CONTRIBUTING.md is currently still not present, feel free to add that file and edit the README.md if you feel something is missing. After that let's merge to master and move the build to master as you suggest. Thanks!

**Comment by raditzlawliet** [comment]
I add
- CONTRIBUTING.md
- CODE_OF_CONDUCT.md

and enhance README.md. 
I'll review the PR and we can merge after that.

**Comment by raditzlawliet** [comment]
We need to add additional info for support in https://github.com/openivity page. 
Adding you and me should be enough for now.
